### ISSUE TITLE
How to patch value of array of objects

### ISSUE THREAD

**Issue by markosimulak** [rpbeukes/angular-typesafe-reactive-forms-helper#228]
Hi!

How I should patch value of form array of objects?
I've tried like this: `form.getSafe(x => x.array).get[index]` but I cant access to controls.
Also, I've tried to cast to `FormGroupControlsOf<A>`  but then `form.array` is undefined.

Example of form group:
```typescript
interface A {
	array: B[];
}

interface B {
	x: string;
	y: string;
}

getFormGroupB(): FormGroupTypeSafe<B> {
	return this._fb.group<B>({
		x: new FormControl(''),
		y: new FormControl('')
	});
}

getFormArrayB(): FormArray {
	return this._fb.array([this.getFormGroupB()]);
}

getFormGroupA(): FormGroupTypeSafe<A> {
	return this._fb.group<A>({
		array: this.getFormArrayB()
	});
}

const form = this.getFormGroupA();
```

So, I wondering how to patch value of 'x' in array with index 0, something like this:
```typescript
form.getSafe(x => x.array).get([0]).controls.x.patchValue('newValue'):
```

Thanks!

**Comment by rpbeukes** [comment]
Hi @markosimulak,

Great to hear you find joy out of this little package 😊.

I have an example of how to do that in one of the tests, [here](https://github.com/rpbeukes/angular-typesafe-reactive-forms-helper/blob/master/tests/__tests__/FormBuilderTypeSafe.spec.ts#L47-L49).
(🤞 Hopefully, it is what you are after  🤞)

At least you'll have a way to patch the value, although I do like your suggestion more :grimacing:. 
Your suggestion reads better, but I'll have to investigate how to make your dream a reality :rocket:.

Feel free to reach out again if it does not solve your issue.
We can work together on a solution for your needs.

Chat soon...
